name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build (if needed)
        run: |
          cd nonprofit-website/src || exit 1
          if [ -f package.json ]; then npm ci && npm run build || true; fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # Set in repo secrets
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Default GitHub Actions token
          action: 'upload'
          app_location: 'nonprofit-website/src'
          api_location: ''
          output_location: ''
